/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharkVentoinhaFlexbreezeHydrogoRouteImport } from './routes/shark-ventoinha-flexbreeze-hydrogo'
import { Route as SharkAspiradorDeMaosRouteImport } from './routes/shark-aspirador-de-maos'
import { Route as MaquinaDeGranizadosNinjaSlushiRouteImport } from './routes/maquina-de-granizados-ninja-slushi'
import { Route as ConsolaNintendoSwitch2MarioKartWorldRouteImport } from './routes/consola-nintendo-switch-2-mario-kart-world'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AspiradorRoboIrobotRoomba105ComboRouteImport } from './routes/aspirador-robo-irobot-roomba-105-combo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentoIdRouteImport } from './routes/pagamento.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicZangiwayWebhookRouteImport } from './routes/api/public/zangiway-webhook'

const SharkVentoinhaFlexbreezeHydrogoRoute =
  SharkVentoinhaFlexbreezeHydrogoRouteImport.update({
    id: '/shark-ventoinha-flexbreeze-hydrogo',
    path: '/shark-ventoinha-flexbreeze-hydrogo',
    getParentRoute: () => rootRouteImport,
  } as any)
const SharkAspiradorDeMaosRoute = SharkAspiradorDeMaosRouteImport.update({
  id: '/shark-aspirador-de-maos',
  path: '/shark-aspirador-de-maos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinaDeGranizadosNinjaSlushiRoute =
  MaquinaDeGranizadosNinjaSlushiRouteImport.update({
    id: '/maquina-de-granizados-ninja-slushi',
    path: '/maquina-de-granizados-ninja-slushi',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsolaNintendoSwitch2MarioKartWorldRoute =
  ConsolaNintendoSwitch2MarioKartWorldRouteImport.update({
    id: '/consola-nintendo-switch-2-mario-kart-world',
    path: '/consola-nintendo-switch-2-mario-kart-world',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AspiradorRoboIrobotRoomba105ComboRoute =
  AspiradorRoboIrobotRoomba105ComboRouteImport.update({
    id: '/aspirador-robo-irobot-roomba-105-combo',
    path: '/aspirador-robo-irobot-roomba-105-combo',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoIdRoute = PagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZangiwayWebhookRoute =
  ApiPublicZangiwayWebhookRouteImport.update({
    id: '/api/public/zangiway-webhook',
    path: '/api/public/zangiway-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aspirador-robo-irobot-roomba-105-combo': typeof AspiradorRoboIrobotRoomba105ComboRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consola-nintendo-switch-2-mario-kart-world': typeof ConsolaNintendoSwitch2MarioKartWorldRoute
  '/maquina-de-granizados-ninja-slushi': typeof MaquinaDeGranizadosNinjaSlushiRoute
  '/shark-aspirador-de-maos': typeof SharkAspiradorDeMaosRoute
  '/shark-ventoinha-flexbreeze-hydrogo': typeof SharkVentoinhaFlexbreezeHydrogoRoute
  '/api/chat': typeof ApiChatRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/api/public/zangiway-webhook': typeof ApiPublicZangiwayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aspirador-robo-irobot-roomba-105-combo': typeof AspiradorRoboIrobotRoomba105ComboRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consola-nintendo-switch-2-mario-kart-world': typeof ConsolaNintendoSwitch2MarioKartWorldRoute
  '/maquina-de-granizados-ninja-slushi': typeof MaquinaDeGranizadosNinjaSlushiRoute
  '/shark-aspirador-de-maos': typeof SharkAspiradorDeMaosRoute
  '/shark-ventoinha-flexbreeze-hydrogo': typeof SharkVentoinhaFlexbreezeHydrogoRoute
  '/api/chat': typeof ApiChatRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/api/public/zangiway-webhook': typeof ApiPublicZangiwayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aspirador-robo-irobot-roomba-105-combo': typeof AspiradorRoboIrobotRoomba105ComboRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consola-nintendo-switch-2-mario-kart-world': typeof ConsolaNintendoSwitch2MarioKartWorldRoute
  '/maquina-de-granizados-ninja-slushi': typeof MaquinaDeGranizadosNinjaSlushiRoute
  '/shark-aspirador-de-maos': typeof SharkAspiradorDeMaosRoute
  '/shark-ventoinha-flexbreeze-hydrogo': typeof SharkVentoinhaFlexbreezeHydrogoRoute
  '/api/chat': typeof ApiChatRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/api/public/zangiway-webhook': typeof ApiPublicZangiwayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aspirador-robo-irobot-roomba-105-combo'
    | '/cart'
    | '/checkout'
    | '/consola-nintendo-switch-2-mario-kart-world'
    | '/maquina-de-granizados-ninja-slushi'
    | '/shark-aspirador-de-maos'
    | '/shark-ventoinha-flexbreeze-hydrogo'
    | '/api/chat'
    | '/pagamento/$id'
    | '/api/public/zangiway-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aspirador-robo-irobot-roomba-105-combo'
    | '/cart'
    | '/checkout'
    | '/consola-nintendo-switch-2-mario-kart-world'
    | '/maquina-de-granizados-ninja-slushi'
    | '/shark-aspirador-de-maos'
    | '/shark-ventoinha-flexbreeze-hydrogo'
    | '/api/chat'
    | '/pagamento/$id'
    | '/api/public/zangiway-webhook'
  id:
    | '__root__'
    | '/'
    | '/aspirador-robo-irobot-roomba-105-combo'
    | '/cart'
    | '/checkout'
    | '/consola-nintendo-switch-2-mario-kart-world'
    | '/maquina-de-granizados-ninja-slushi'
    | '/shark-aspirador-de-maos'
    | '/shark-ventoinha-flexbreeze-hydrogo'
    | '/api/chat'
    | '/pagamento/$id'
    | '/api/public/zangiway-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AspiradorRoboIrobotRoomba105ComboRoute: typeof AspiradorRoboIrobotRoomba105ComboRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConsolaNintendoSwitch2MarioKartWorldRoute: typeof ConsolaNintendoSwitch2MarioKartWorldRoute
  MaquinaDeGranizadosNinjaSlushiRoute: typeof MaquinaDeGranizadosNinjaSlushiRoute
  SharkAspiradorDeMaosRoute: typeof SharkAspiradorDeMaosRoute
  SharkVentoinhaFlexbreezeHydrogoRoute: typeof SharkVentoinhaFlexbreezeHydrogoRoute
  ApiChatRoute: typeof ApiChatRoute
  PagamentoIdRoute: typeof PagamentoIdRoute
  ApiPublicZangiwayWebhookRoute: typeof ApiPublicZangiwayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shark-ventoinha-flexbreeze-hydrogo': {
      id: '/shark-ventoinha-flexbreeze-hydrogo'
      path: '/shark-ventoinha-flexbreeze-hydrogo'
      fullPath: '/shark-ventoinha-flexbreeze-hydrogo'
      preLoaderRoute: typeof SharkVentoinhaFlexbreezeHydrogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shark-aspirador-de-maos': {
      id: '/shark-aspirador-de-maos'
      path: '/shark-aspirador-de-maos'
      fullPath: '/shark-aspirador-de-maos'
      preLoaderRoute: typeof SharkAspiradorDeMaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquina-de-granizados-ninja-slushi': {
      id: '/maquina-de-granizados-ninja-slushi'
      path: '/maquina-de-granizados-ninja-slushi'
      fullPath: '/maquina-de-granizados-ninja-slushi'
      preLoaderRoute: typeof MaquinaDeGranizadosNinjaSlushiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consola-nintendo-switch-2-mario-kart-world': {
      id: '/consola-nintendo-switch-2-mario-kart-world'
      path: '/consola-nintendo-switch-2-mario-kart-world'
      fullPath: '/consola-nintendo-switch-2-mario-kart-world'
      preLoaderRoute: typeof ConsolaNintendoSwitch2MarioKartWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspirador-robo-irobot-roomba-105-combo': {
      id: '/aspirador-robo-irobot-roomba-105-combo'
      path: '/aspirador-robo-irobot-roomba-105-combo'
      fullPath: '/aspirador-robo-irobot-roomba-105-combo'
      preLoaderRoute: typeof AspiradorRoboIrobotRoomba105ComboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$id': {
      id: '/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/pagamento/$id'
      preLoaderRoute: typeof PagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zangiway-webhook': {
      id: '/api/public/zangiway-webhook'
      path: '/api/public/zangiway-webhook'
      fullPath: '/api/public/zangiway-webhook'
      preLoaderRoute: typeof ApiPublicZangiwayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AspiradorRoboIrobotRoomba105ComboRoute:
    AspiradorRoboIrobotRoomba105ComboRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConsolaNintendoSwitch2MarioKartWorldRoute:
    ConsolaNintendoSwitch2MarioKartWorldRoute,
  MaquinaDeGranizadosNinjaSlushiRoute: MaquinaDeGranizadosNinjaSlushiRoute,
  SharkAspiradorDeMaosRoute: SharkAspiradorDeMaosRoute,
  SharkVentoinhaFlexbreezeHydrogoRoute: SharkVentoinhaFlexbreezeHydrogoRoute,
  ApiChatRoute: ApiChatRoute,
  PagamentoIdRoute: PagamentoIdRoute,
  ApiPublicZangiwayWebhookRoute: ApiPublicZangiwayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
