// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkztqodvqqfkcwyjkhnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrenRxb2R2cXFma2N3eWpraG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzMjk3NTgsImV4cCI6MjA5NzkwNTc1OH0.TWNRu3mj7Sk8sFkDUjhpjEYeAG1nv0TpxJBlpSliiNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});